package actions

// Smithing
const MAKE_BRONZE = "MAKE_BRONZE"
const MAKE_IRON = "MAKE_IRON"
const MAKE_STEEL = "MAKE_STEEL"
const MAKE_MITHRIL = "MAKE_MITHRIL"
const MAKE_ADAMANT = "MAKE_ADAMANT"
const MAKE_RUNE = "MAKE_RUNE"
const MAKE_SILVER = "MAKE_SILVER"
const MAKE_GOLD = "MAKE_GOLD"